### ISSUE TITLE
Top Navigation Changes

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/JC_Theme#1]
-	Change the interaction on Apply, Visit, Request info. Instead of the line underneath and the text moving up could it just fade into white on hover?
-	I like the hover effect on the e-services, etc. links at the top, but can we do that with the email link as well instead of the white box on hover? Also, can we remove the letter icon next to e-mail? So all the e-mail, e-services, etc..links should hover the same
-	Could we bump up the email, e-services links text one point size and go down a point size with the apply, visit, request info text? 
-	Could we make the logo a little bit larger

**Comment by joelworsham** [comment]
For the underline animation, I want to present a consistent experience to the user, and I feel that the underline animation (as also used on the personas section, and potentially other places on the site) is a great indicator of a link. I figured starting it off that way in the header was a great way to get the user used to this experience, and it is pleasing aesthetically. I am definitely open to changing it though.
 
For the email link, I feel it needs to be prominent. You stated that a *lot* of students will be coming to the site just for email, so I feel that it should stand out from the other links and be easy to identify and find (which is why I added the well-recognized icon next to it). What do you think?

**Comment by banksashleym** [comment]
Could we keep it how I have styled and change the underline on the apply now links to a hover effect and remove the email icon? We don't currently give any special treatment to the e-mail icon, so it should be ok. Thanks!
