### ISSUE TITLE
Hero Image Text changes

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/JC_Theme#2]
-	For the text over the hero image, could we make the headline a little larger and do a serif font? 
-	These are going to be linking to feature stories, could we re-phrase the “Discover Jackson College” to say “Read More” and make that box much smaller. The headline should be the dominant feature and the “Read More” should be the secondary feature. We like the hover interaction on the button.
-	Please move the placement of the text and read more button just a little closer to the bottom of the image. (in your placeholder image, start the text right about where her notebook is?)

**Comment by joelworsham** [comment]
Do you have any specific font in mind? I only stuck with Open Sans because I thought you only wanted one font for the site, but I am definitely open to introducing another font. Do you know if this alternate font will be used anywhere else on the site? If the font is only used on the home page, I will make sure to program accordingly to reduce page load times on subsequent pages.

I will make those changes to the "Read More" button (I will refer to this as the CTA button from here-on out, which is "Call To Action" button). I also made sure the button text is fully editable by site administrators in the "Edit Page" screen for the home page :)

**Comment by banksashleym** [comment]
Could we do Droid Serif for the serif font? I would like to possible style a header or two (not any of the main ones, but maybe an h4/5 header) with this font as well.

**Comment by joelworsham** [comment]
Okay sure thing. Let's give it a try!
