### ISSUE TITLE
Inside pages

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/JC_Theme#5]
Inside Pages
-	Could there be more padding between  where the gray navigation background ends and the main content begins? For example, on the Academics  inside page, the “prepared to be the best” and paragraphs underneath should be moved to the right to allow more space between the navigation box and content.
-	Could we take down the size of the paragraph text a point size?
-	For the breadcrumbs, can we reverse the colors and have the active page be the bold burgundy color and the trail of pages be the regular weight gray color?
-	For the inside pages, could we tweak the navigation and main content to appear more like this example? http://jackson-college-website.webflow.io/academics (for instance the size of the text in the navigation can be taken down a few point sizes, the padding/text on the buttons can be taken down so they are a little smaller, more padding around the main content columns)
-	I would like the academics header that is in the burgundy bar to remain the same across all academics pages. So when someone is in the Academics section, that headline will remain constant. Same with Cost & Aid, etc…Then when someone navigates to a new page, I would like the active page to be in the bold maroon color in the side navigation that the “welcome” is on the academics inside page. Let me know if that doesn't make sense :)

**Comment by joelworsham** [comment]
For the breadcrumbs question, I would advise against this. Throughout the site, links will be highlighted in the content by being a purple color. Gray colors typically will indicate to the user that the text is not clickable, and purple colors typically will indicate to the user that the text _is_ clickable. In this case, we would be reversing the color scheme so that the purple text is _not_ clickable. I think this might end up confusing users in the end.

For the academics header, it was my impression that the burgundy bar is where the page title lives. Is this not the case? If not, where would the page title be displayed? It is very important for user experience that the page title be visible somewhere so they can clearly identify where they are. I personally think the burgundy bar being the page title would be a good route to go. I do understand that the sidebar is an indicator to where the user is, but it's not prominent or typical for a user to look there for page identification.

Thoughts?

**Comment by banksashleym** [comment]
Ahh, I see what you mean about the breadcrumbs...maybe the boldness is what's throwing me off. Could we remove the boldness from all of the breadcrumbs and keep the colors the same? To me, boldness should indicate that's the page you are on? I think that should fix the issue :)

I agree with the page title, let's keep that how you have it :)
