### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/JC_Theme#7]
-We used www.wm.edu as a benchmarking college and really liked their design. I noticed that their content is spread out wider on the screen with less white space on either side of the "main content". Could we do this with our site as well? I think especially on the inside pages, being able to spread the content out a little further would be helpful.

**Comment by joelworsham** [comment]
I guess I don't understand the question? The main content container width is almost the same on www.wm.edu as it is on jacksoncollege.staging.wpengine.com

Perhaps I'm not understanding what you're asking?

**Comment by banksashleym** [comment]
It just seems like the main content is quite a bit smaller than the websites we have modeled ours after. I'm just worried that with so much negative space on either side of the page, it's not going to leave much room if we have a page with a lot of content? For example, if we have a page with the left hand navigation, then the main content, and then a right sidebar as well, the middle column seems very narrow. Could we make it more like Cornerstone's width? Here is an example of what I'm talking about:
http://www.jccmi.edu/NewWebsite/images.html

**Comment by joelworsham** [comment]
I will make the main content column wider. It's currently 1000px, I'll raise it to 1200px and give that a try.

Just so you're aware, the entire site, on every page, can be thought of as existing in a column. Some elements don't exist inside this column, like the hero image on the home page, but most everything else lives inside this column. This provides for a very consistent viewing experience as well as nice clean "lines" on both sides. So when I refer to the "content column" or "site width" or something, it's all the same. So when I expand this container from 1000px to 1200px, it will be site-wide (header, content, footer, etc). But 1200px is still a completely reasonable container width, so let's give it a try.

One note though, it is important to change the mentality a bit. Rather than thinking about the white space on either side, think about the width of the site instead. The reason for this thinking is that there is no way to tell how wide or narrow someone's screen will be. So if someone's screen is 1000px and our site width is 1000px, there will be no white space, but if someone's screen (or projector) is closer to 1600px, there will be 200px of whitespace on either side. The important thing to note here though is that regardless of how much white space is on either side, the content width will be the same for both screens, so that's where we need to shift our attention, the common element.

**Comment by banksashleym** [comment]
That would be great, thanks!

Thanks for the understanding too - that makes sense to think of it that way.
